config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :households do
    resources :bills
  end
  root 'households#index'
  resources :home, only: [:index]
end

app/models/bill.rb
class Bill < ActiveRecord::Base
  belongs_to :household

  validates :amount, presence: true
  validates :date, presence: true
  validates :kind, presence: true
  validates :kind, inclusion: { in: ["Electric", "Gas", "Water"] }
  validates :kind, uniqueness: { scope: :date }
end

app/models/household.rb
class Household < ActiveRecord::Base
  belongs_to :user

  validates :address, presence: true
  validates :city, presence: true
  validates :state, presence: true
  validates :zip, presence: true
  validates :zip, length: { is: 5 }
  validates :zip, numericality: { only_integer: true }
  validates :occupants, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable,
    :registerable,
    :recoverable,
    :rememberable,
    :trackable,
    :validatable

  has_many :households

  validates :username, presence: true
end

app/models/utilitydata.rb
class Utilitydata < ActiveRecord::Base
  validates :state, presence: true
  validates :date, presence: true
  validates :amount, presence: true
  validates :kind, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF amay want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :username
  end
end

app/controllers/bills_controller.rb
class BillsController < ApplicationController
  def new
    @user = current_user
    @household = Household.find(params[:household_id])
    @bill = Bill.new
    @kinds = ["Electric", "Gas", "Water"]
  end

  def create
    @user = current_user
    @household = Household.find(params[:household_id])
    @bill = Bill.new(bill_params)
    @bill.household = @household
    @kinds = ["Electric", "Gas", "Water"]
    if @bill.save
      @bill.update(date: "#{@bill.date.year}/#{@bill.date.month}/1")
      flash[:notice] = "Bill Created Successfully"
      redirect_to household_path(@household)
    else
      flash[:errors] = @bill.errors.full_messages.join(". ")
      render :new
    end
  end

  def edit
    @user = current_user
    @household = Household.find(params[:household_id])
    @bill = Bill.find(params[:id])
    @kinds = ["Electric", "Gas", "Water"]
  end

  def update
    @user = current_user
    @household = Household.find(params[:household_id])
    @bill = Bill.find(params[:id])
    @kinds = ["Electric", "Gas", "Water"]
    if @bill.update(bill_params)
      @bill.update(date: "#{@bill.date.year}/#{@bill.date.month}/1")
      flash[:notice] = "Bill updated successfully"
      redirect_to household_path(@household)
    else
      flash[:errors] = @bill.errors.full_messages.join(". ")
      render :edit
    end
  end

  def destroy
    @household = Household.find(params[:household_id])
    Bill.find(params[:id]).destroy
    redirect_to household_path(@household)
  end

  def show
    @user = current_user
    @household = Household.find(params[:household_id])
    @bill = Bill.find(params[:id])
    @bills = Bill.where(date: @bill.date, household_id: @bill.household_id)
    if @bills.length == 1
      flash[:notice] = "Please add more bills for this month to see breakdown"
    end
    d = []
    @bills.each do |bill|
      d << [bill.kind, bill.amount]
    end
    @data = Utilitydata.where(state: @household.state, kind: @bill.kind,
                              date: @bill.date).first
    if @data == nil
      @data = Utilitydata.new(state: @household.state, kind: @bill.kind,
                              date: @bill.date, amount: 10000000)
    end
    text = "Breakdown for #{@bill.date.month}/#{@bill.date.year}"
    @chart3 = LazyHighCharts::HighChart.new('pie') do |f|
      f.chart({ defaultSeriesType: "pie", margin: [50, 200, 60, 170] } )
      series = {
        type: 'pie',
        name: 'Amount($)',
        data: d
      }
      f.series(series)
      f.options[:title][:text] = text
      f.legend(layout: 'vertical', style: {
        left: 'auto', bottom: 'auto', right: '50px', top: '100px'
      })
      f.plot_options(pie: {
        allowPointSelect: true,
        cursor: "pointer",
        dataLabels: {
          enabled: true,
          color: "black",
          style: {
            font: "13px Trebuchet MS, Verdana, sans-serif"
          }
        }
      })
    end
  end

  private

  def bill_params
    params.require(:bill).permit(:amount, :date, :kind)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/households_controller.rb
class HouseholdsController < ApplicationController
  def index
    if user_signed_in?
      @user = current_user
      @households = Household.where(user: @user)
    else
      redirect_to home_index_path
    end
  end

  def new
    @user = current_user
    @household = Household.new
  end

  def create
    @user = current_user
    @household = Household.new(household_params)
    @household.user = current_user
    if @household.save
      flash[:notice] = "Household Created Successfully"
      redirect_to households_path
    else
      flash[:errors] = @household.errors.full_messages.join(". ")
      render :new
    end
  end

  def edit
    @user = current_user
    @household = Household.find(params[:id])
  end

  def update
    @user = current_user
    @household = Household.find(params[:id])
    if @household.update(household_params)
      flash[:notice] = "Household updated successfully"
      redirect_to households_path
    else
      flash[:errors] = @household.errors.full_messages.join(". ")
      render :edit
    end
  end

  def destroy
    Household.find(params[:id]).destroy
    redirect_to households_path
  end

  def show
    @user = current_user
    @household = Household.find(params[:id])
    @bills = Bill.where(household: @household)
  end

  private

  def household_params
    params.require(:household).permit(:address, :city, :state, :zip, :occupants)
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  protected

  def update_resource(resource, params)
    resource.update_without_password(params)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bills/edit.html.erb
<%= render "/layouts/bill_form"%>

app/views/bills/new.html.erb
<%= render "/layouts/bill_form"%>

app/views/bills/show.html.erb
<%@bills.each do |bill|%>
  <%=bill.amount%>
<%end%>
<%=@data.amount%>
<%=high_chart("some_id", @chart3)%>

app/views/home/index.html.erb
<div class="row medium-12 back-1 pad-vert center">
  <h3 class="font-white center">
    UtiliTrak
    <hr></hr>
  </h3>
  <h4 class="font-white center">
    Save Energy, Live Smart
  </h4>
  <p><a href="/users/sign_in" class="button">Sign In</a></p>
  <p><a href="/users/sign_up" class="button">Sign Up</a></p>
</div>
<div class="columns medium-12">
  <h3 class="center font-blue">How It Works</h3>
  <hr></hr>
  <div class="columns small-4">
    <div class="callout secondary">
      <p><%= image_tag "house.png"%></p>
      <p>Create a Household to store all your utility information</p>
    </div>
  </div>
  <div class="columns small-4">
    <div class="callout secondary">
      <%= image_tag "dollar.png"%>
      <p>Create bills by simply inputting a monthly bill amount</p>
    </div>
  </div>
  <div class="columns small-4">
    <div class="callout secondary">
      <p><%= image_tag "chart.png"%></p>
      <p>See data analysis for energy consumption and trends</p>
    </div>
  </div>
</div>

app/views/households/edit.html.erb
<% if user_signed_in? %>
  <h1>This is where we'll update a household</h1>

  <%= form_for(@household) do |f| %>
    <%= f.label :address %>
    <%= f.text_field :address, value: @household.address %>
      <br>
    <%= f.label :city %>
    <%= f.text_field :city, value: @household.city %>
      <br>
    <%= f.label :state %>
    <%= f.text_field :state, value: @household.state %>
      <br>
    <%= f.label :zip %>
    <%= f.text_field :zip, value: @household.zip %>
      <br>
    <%= f.submit "Update Household" %>
  <% end %>

  <%= link_to "Back to Home Page", root_path %>
<% else %>
  <h2>Need to be signed in to update household!</h2>
<% end %>

app/views/households/index.html.erb
<% if user_signed_in? %>
  <h1><%=current_user.username%>'s Households<h1>
  <%@households.each_with_index do |household,i|%>
    <div class="house-list">
      <ul>
        <li><%=i+1%>.</li>
        <li><a href="/households/<%= household.id %>" id="house<%=household.id%>">
          <%= image_tag "house.png"%>
        </a></li>
        <li>Address: <%= household.address %></li>
        <li><%= link_to 'Delete Household', household_path(household.id), data: { confirm: 'Are you sure?' }, method: :delete %></li>
        <li><%= link_to 'Edit Household', edit_household_path(household.id) %></li>
      </ul>
    </div>
  <%end%>
  <%= link_to 'Add a Household', new_household_path%>
<%else%>
  <h2>Need to be signed in to see your households!</h2>
<%end%>
<!-- <img alt="Mona Lisa" src="http://i.stack.imgur.com/OyP0g.jpg" title="original">
<img alt="Mona Lisa" src="http://i.stack.imgur.com/OyP0g.jpg" title="saturate" class="saturate">
<img alt="Mona Lisa" src="http://i.stack.imgur.com/OyP0g.jpg" title="grayscale" class="grayscale">
<img alt="Mona Lisa" src="http://i.stack.imgur.com/OyP0g.jpg" title="contrast" class="contrast">
<img alt="Mona Lisa" src="http://i.stack.imgur.com/OyP0g.jpg" title="brightness" class="brightness">
<img alt="Mona Lisa" src="http://i.stack.imgur.com/OyP0g.jpg" title="blur" class="blur">
<img alt="Mona Lisa" src="http://i.stack.imgur.com/OyP0g.jpg" title="invert" class="invert">
<img alt="Mona Lisa" src="http://i.stack.imgur.com/OyP0g.jpg" title="sepia" class="sepia">
<img alt="Mona Lisa" src="http://i.stack.imgur.com/OyP0g.jpg" title="huerotate" class="huerotate">
<img alt="Mona Lisa" src="http://i.stack.imgur.com/OyP0g.jpg" title="opacity" class="rss opacity"> -->

app/views/households/new.html.erb
<% if user_signed_in? %>
  <h1>Create a New Household</h1>

  <%= form_for(@household) do |f| %>
    <%= f.label :address %>
    <%= f.text_field :address %>
      <br>
    <%= f.label :city %>
    <%= f.text_field :city %>
      <br>
    <%= f.label :state %>
    <%= f.text_field :state %>
      <br>
    <%= f.label :zip %>
    <%= f.text_field :zip %>
      <br>
    <%= f.submit "Create Household" %>
  <% end %>

  <%= link_to "Back to Home Page", root_path %>
<% else %>
  <h2>Need to be signed in to add a house!</h2>
<% end %>

app/views/households/show.html.erb
<% if user_signed_in? %>
  <%@bills.each_with_index do |bill, i|%>
    <div class="bill-list">
      <ul>
        <li><%=i+1%>.</li>
        <li><a href="/households/<%= @household.id %>/bills/<%=bill.id%>" id="bill<%=bill.id%>">
          <%= image_tag "#{bill.kind}.png"%>
        </a></li>
        <li>Date: <%= bill.date %></li>
        <li><%= link_to 'Delete Bill', household_bill_path(@household,bill.id), data: { confirm: 'Are you sure?' }, method: :delete %></li>
        <li><%= link_to 'Edit Bill', edit_household_bill_path(@household,bill.id) %></li>
      </ul>
    </div>
  <%end%>
  <%= link_to 'Add a Bill', new_household_bill_path(@household)%>
<%else%>
  <h2>Need to be signed in to see your bills!</h2>
<%end%>

app/views/layouts/_bill_form.html.erb
<link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
  <script src="http://code.jquery.com/jquery-1.9.1.js"></script>
  <script src="http://code.jquery.com/ui/1.10.2/jquery-ui.js"></script>
  <script>
   $(function() {
     $( "#datepicker" ).datepicker({
       altFormat: "dd M yy",
       dateFormat: "dd M yy",
     });
   });
  </script>

<% if user_signed_in? %>
  <h1>Create a New Bill</h1>

  <%= form_for [@household, @bill] do |f| %>
    <%= f.label :amount, "Amount ($)" %>
    <%= f.text_field :amount %>
      <br>
    <%= f.label :date %>
    <%= f.text_field :date, :id => "datepicker" %>
      <br>
    <%= f.label :kind %>
    <%= f.select(:kind, options_for_select(@kinds))%>
      <br>
    <%= f.submit "Generate Bill" %>
  <% end %>

  <%= link_to "Back to Home Page", root_path %>
<% else %>
  <h2>Need to be signed in to add a bill!</h2>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "UtiliTrak" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <nav class="top-bar" data-topbar role="navigation">
      <ul class="title-area">
    <li class="name">
      <h1><a href="/">UtiliTrak</a></h1>
    </li>
    <li class="toggle-topbar menu-icon"><a href="#"><span></span></a></li>
  </ul>

  <section class="top-bar-section">
    <!-- Right Nav Section -->
    <ul class="right">
      <% if user_signed_in? %>
        <li><strong><%= link_to 'Sign Out', destroy_user_session_path, method: :delete %></strong></li>
        <li><strong><%= link_to 'Edit Info', edit_user_registration_path%></strong></li>
      <% else %>
        <li><strong><%= link_to 'Sign In', new_user_session_path %></strong></li>
        <li><strong><%= link_to 'Sign Up', new_user_registration_path %></strong></li>
      <% end %>
      <!-- <li class="active"><a href="#">Right Button Active</a></li>
      <li class="has-dropdown">
        <a href="#">Right Button Dropdown</a>
        <ul class="dropdown">
          <li><a href="#">First link in dropdown</a></li>
          <li class="active"><a href="#">Active link in dropdown</a></li>
        </ul>
      </li> -->
    </ul>
    <!-- Left Nav Section -->
    <!-- <ul class="left">
      <li><a href="#">Left Nav Button</a></li>
    </ul> -->
  </section>
</nav>

      <div class="row">
        <% flash.each do |key, value| %>
          <div data-alert class="alert-box radius flash <%= key %>">
            <%= value %>
            <a href="#" class="close">&times;</a>
          </div>
        <% end %>
      </div>
    <%= yield %>

  </body>
</html>